# Generated by Django 6.1.1 on 2026-09-20 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Avarias, marca, modelo ou detalhes técnicos', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Ex: Notebooks, Tablets', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='inventario.categoria'),
        ),
    ]
