# Generated by Django 6.1 on 2026-08-30 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('RETIRADO', 'Retirado (Em Andamento)'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='SOLICITADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
