# Generated by Django 6.1.1 on 2026-09-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
