# Generated by Django 6.1.1 on 2026-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_data_devolucao_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='prorrogacao_solicitada',
            field=models.BooleanField(default=False),
        ),
    ]
