# Generated by Django 5.1.4 on 2026-09-03 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_informado', models.EmailField(help_text='Guardado mesmo se o e-mail não existir no sistema, para fins de auditoria.', max_length=254)),
                ('tipo_evento', models.CharField(choices=[('SOLICITACAO_RECUPERACAO', 'Solicitação de recuperação'), ('RECUPERACAO_SUCESSO', 'Recuperação concluída'), ('RECUPERACAO_FALHA', 'Recuperação falhou')], max_length=30)),
                ('detalhe', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_autenticacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(editable=False)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
