# Generated by Django 6.1.1 on 2026-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_logautenticacao_tokenrecuperacaosenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logautenticacao',
            name='email_informado',
            field=models.EmailField(blank=True, help_text='Guardado mesmo se o e-mail não existir no sistema, para fins de auditoria.', max_length=254),
        ),
        migrations.AlterField(
            model_name='logautenticacao',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITACAO_RECUPERACAO', 'Solicitação de recuperação'), ('RECUPERACAO_SUCESSO', 'Recuperação concluída'), ('RECUPERACAO_FALHA', 'Recuperação falhou'), ('DOISFA_ATIVADO', '2FA ativado'), ('DOISFA_DESATIVADO', '2FA desativado'), ('DOISFA_SUCESSO', '2FA validado com sucesso'), ('DOISFA_FALHA', '2FA falhou')], max_length=30),
        ),
    ]
