# Generated by Django 6.1.1 on 2026-09-11 22:43

import usuarios.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_logautenticacao_email_informado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=usuarios.crypto.CampoCriptografado(blank=True, help_text='Telefone pessoal, armazenado criptografado com Fernet (item 3.4).', max_length=255, null=True),
        ),
    ]
