# Generated by Django 6.1 on 2026-09-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='consentimento_dados',
            field=models.BooleanField(default=False, help_text='Indica se o usuário aceitou os termos de uso e privacidade (LGPD 4.4 e 4.5)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_consentimento',
            field=models.DateTimeField(blank=True, help_text='Data e hora exata do aceite (LGPD 4.7)', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='versao_documento_aceito',
            field=models.CharField(blank=True, help_text='Versão da Política de Privacidade aceita (ex: v1.0) (LGPD 4.7)', max_length=10, null=True),
        ),
    ]
