# Generated by Django 6.1.1 on 2026-09-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_consentimento_dados_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAutenticacao',
        ),
    ]
