# Generated by Django 6.1.1 on 2026-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN_SUCESSO', 'Login com Sucesso'), ('LOGIN_FALHA', 'Falha no Login'), ('2FA_SUCESSO', 'Sucesso no 2FA'), ('2FA_FALHA', 'Falha no 2FA'), ('RECUPERACAO', 'Recuperação de Senha'), ('RECUPERACAO_SOLICITADA', 'Solicitação de Recuperação'), ('RECUPERACAO_SUCESSO', 'Recuperação com Sucesso'), ('RECUPERACAO_FALHA', 'Falha na Recuperação')], max_length=50),
        ),
    ]
